export const GET_TODO = 'GET_TODO'
export const LIST_TODOS = 'LIST_TODOS'
export const CREATE_TODO = 'CREATE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const ERROR_TODO = 'ERROR_TODO'
export const TODO_RESET = 'TODO_RESET'
export const DELETE_TODO = 'DELETE_TODO'
